name: SpotifyThingy
version: '${project.version}'
main: aroze.me.spotifythingy.SpotifyThingy
api-version: 1.18
authors: [ Aroze ]
description: A cool thingy for Spotify integration with your Minecraft server
commands:
  testauth: {}
  play:
    aliases: [ resume ]
  pause: {}